const Customer = [
  {
    CID: "C0001",
    fname: "FOOD & TASTE",
    lname: null,
    email: null,
    phoneno: "03074411112",
    houseno: "75W E",
    strname: "Block F",
    townname: "Punjab CHS",
    city: "Lahore",
  },
  {
    CID: "C0002",
    fname: "PUNJAB",
    lname: "HOTEL",
    email: null,
    phoneno: "04235822435",
    houseno: "435D",
    strname: "Block D",
    townname: "Punjab CHS",
    city: "Lahore",
  },
  {
    CID: "C0003",
    fname: "DOGAR",
    lname: "RESTAURANT",
    email: null,
    phoneno: "03000777467",
    houseno: null,
    strname: "Street 11 Block Y",
    townname: "DHA Phase 3",
    city: "Lahore",
  },
  {
    CID: "C0004",
    fname: "DOGAR",
    lname: "RESTAURANT",
    email: null,
    phoneno: "03006311117",
    houseno: null,
    strname: "Rehman Centre 2 Block M",
    townname: "DHA Phase 5 ASKARI 11",
    city: "Lahore",
  },
  {
    CID: "C0005",
    fname: "DOGAR",
    lname: "RESTAURANT",
    email: null,
    phoneno: "03002222133",
    houseno: "55-T",
    strname: "near optp Block T",
    townname: "DHA Phase 2",
    city: "Lahore",
  },
  {
    CID: "C0006",
    fname: "CHATKHARA",
    lname: null,
    email: null,
    phoneno: "04235723597",
    houseno: "H-14",
    strname: "147 Street 15",
    townname: "DHA Phase 1",
    city: "Lahore",
  },
  {
    CID: "C0007",
    fname: "MASALAWALA",
    lname: null,
    email: "masalawala212@gmail.com",
    phoneno: "03088789789",
    houseno: "9-e-2",
    strname: "Block E 2",
    townname: "Gulberg III",
    city: "Lahore",
  },
  {
    CID: "C0008",
    fname: "MEAT",
    lname: "REPUBLIC",
    email: "meatrepublic555@gmail.com",
    phoneno: "03180452171",
    houseno: "27-A",
    strname: "next to JalalSons",
    townname: "Commercial Area Izmir",
    city: "Lahore",
  },
  {
    CID: "C0009",
    fname: "THE",
    lname: "WOK",
    email: "twk@gmail.com",
    phoneno: "03200113854",
    houseno: null,
    strname: "MALL 1 Main Blvd",
    townname: "Block D1 Gulberg III",
    city: "Lahore",
  },
  {
    CID: "C0010",
    fname: "BAZ BAN",
    lname: "BIRYANI",
    email: null,
    phoneno: "03004113427",
    houseno: null,
    strname: "Kasur Rd",
    townname: "Shadab Garden",
    city: "Lahore",
  },
  {
    CID: "C0011",
    fname: "TOFU  CHINESE",
    lname: "& THAI FOOD",
    email: "tofu@outlook.com",
    phoneno: "03248493551",
    houseno: "6B",
    strname: "near button corner",
    townname: "Ghalib Market Gulberg 3",
    city: "Lahore",
  },
  {
    CID: "C0012",
    fname: "ALI",
    lname: "IRFAN",
    email: null,
    phoneno: "03006734111",
    houseno: "55-C",
    strname: "Abu Bakr Street",
    townname: "Johar Town",
    city: "Lahore",
  },
  {
    CID: "C0013",
    fname: "MUHAMMAD",
    lname: "ASLAM",
    email: null,
    phoneno: "03208115630",
    houseno: "178-G",
    strname: null,
    townname: "Lake City",
    city: "Lahore",
  },
  {
    CID: "C0014",
    fname: "MS. AYESHA",
    lname: "KHAN",
    email: null,
    phoneno: "03147834909",
    houseno: "241-C",
    strname: "Barkat Market",
    townname: "Garden Town",
    city: "Lahore",
  },
];
module.exports = { data: Customer };
